snyk/code-client

CHANGELOG.md, development.md, package-lock.json, package.json, src/constants/errors.ts, src/dto/report-error.request.dto.ts, src/dto/report-error.response.dto.ts, src/enums/request-types.enum.ts, src/index.ts, src/interfaces/service-ai.interface.ts, src/modules/Http.ts, src/modules/ServiceAI.ts, tests/ServiceAI.spec.ts, tests/mocks/mock-server.ts, tests/mocks/requests.ts, tests/mocks/responses.ts
=> Added ReportError API endpoint.

package-lock.json, package.json, src/files.ts
flat-cache doesn't provide default export, therefore it was failing a compilation.
=> fix: flat-cache doesn't provide default export

src/http.ts
It's better to send security related token as headers, as they will not be logged, unlike querystrings.
This PR depends on https://github.com/DeepCodeAI/product/pull/631
=> sent custom oAuthToken as a header, not a query param

CHANGELOG.md, package-lock.json, package.json, src/analysis.ts, src/http.ts
A new `username` param as part of `analyzeGit` to support our `BitBucket Cloud` integration
=> Add username param to analyzeGit

src/interfaces/analysis-result.interface.ts, src/sarif_converter.ts, tests/api.spec.ts
This PR depends on https://github.com/DeepCodeAI/product/pull/685
The tests seam to fail locally (to test them, run `DEEPCODE_URL=http://localhost:8080 npm run test`). This is probably due to the `multifile-markers` engine version having a different knowledgebase than usual.
However it also seams we don't have tests for the SARIF formatter, please @Spoor2709 review this as well and try to check the validity of the markers URI.
=> Added markers interfile position

package.json
Add forgotten steps to package.json
=> fix: build from typescript before publish

src/analysis.ts, tests/analysis.spec.ts
Adding support for sarif on `analyzeFolders` response payload
=> feat: add sarif support to analyzeFolders

src/interfaces/analysis-result.interface.ts, src/sarif_converter.ts, tests/sarif_converter.spec.ts
COD-114 Storing automatic fix examples on our DB
🗄️ Example commit fixes need to be stored in our database.
✅ Exporting the `ExampleCommitFix` interface to make it accessible to the Sarif Converter.
✅ Updating the `properties` object on `rules` instances of the Sarif Converter to be able to store them.
✅ Updating the Sarif Converter spec to test for the presence of the exemple `ExampleCommitFix`.
- Check the new `RuleProperty` type and its use.
- Run the `tests/sarif_converter.spec.ts` test.
- Run the `tests/sarif_converter.spec.ts` test.
=> feat: adding commit fixes and descriptions to the rules' properties

package.json, src/files.ts, tests/git.analysis.spec.ts
[COD-268]
This Pr upgrades to our patched version of fast-globs
Code Client is used in the snyk cli which is an open source repo and can not have any vulns. glob-parent was a dependancy in the dependancy tree with a regex ddos vuln that snyk found after contecting the maintainer he was very rude and did not seem to want to push the fixes that had been approved. So this is a temporary fix until the maintainer pushes the fixes.
[COD-268]: https://snyksec.atlassian.net/browse/COD-268
=> [COD-268] fix: upgrade fast-globs to snyk patch

src/analysis.ts, src/bundles.ts, src/lib/utils.ts, tests/api.spec.ts, tests/utils.spec.ts
we're using `code-client` on the CLI so we need it to support the minimum version the cli support. which is node 10.
Which doesn't support `object.fromEntries`. This pr uses an internal version of this functionality, that should work the same
This is tested against the same test `object.fromEntries` has on MDN
=> fix: object.fromEntries not supported node10

src/interfaces/analysis-result.interface.ts, src/sarif_converter.ts, tests/__snapshots__/api.spec.ts.snap, tests/api.spec.ts
This PR removes the possibility of having a tag break the category filtering by giving categories it own place in the property bag
This also changes the analysisResults.files[filePath] test to a snapshot due to constant updating of the fingerprinting
=> fix: add catergories in a seperate property field in the property bag

src/axios.ts
Under heavy load i realized, that we don't reuse connections and establish new one al the time. At some point, we just can't make a new connection and everything hangs.
This PR aims to solve this by setting special http/https agent with keep alive and granular socket settings
=> feat: axios agent keep alive to reuse connections

src/axios.ts, tests/api.spec.ts, tests/git.analysis.spec.ts
To unify behaviour with default `snyk test` command, this PR takes an advantage of https://github.com/snyk/snyk/commit/5ae3182e16929b0d6ac87a976194c599b22835e3#diff-1bc78dd2ada161f97e1a1e595957fbe2487468b6a81191600acf0aa63769ad88R136
=> Fix: Propagate --insecure parameter

tests/api.spec.ts
Fix failing tests discovered in (but unrelated to) #83.
=> test: remove java-dummy

.circleci/config.yml
Since `@snyk/snyk` still supports node v10, and uses `@snyk/code-client`, `code-client` should be tested with node v10 as well.
=> [COD-300] test: run tests with node 10 as well

tests/git.analysis.spec.ts
Adds a tests to test reachability following the introduced missing args in https://github.com/snyk/code-client/pull/81. 
The reason these were not there before is that new `suggestion` image was not yet deployed and it is needed in order to successfully run the tests.
=> Cod 409/reachability fix tests

src/analysis.ts, src/index.ts, tests/analysis.spec.ts
Exposes `createBundleFromFolders` method which creates a bundle remotely and returns `bundleId`. The logic is extracted and reused (with some caveats) in the `analyzeFolders` method.
\-
\-
This is being done to allow us to separate logic which uploads and which analyses so that we can perform this in separate steps.
=> feat: expose bundle creation logic

package.json
Solves `npm WARN deprecated @types/multimatch@4.0.0: This is a stub types definition. multimatch provides its own type definitions, so you do not need this installed.`
as requested here:
https://snyk.slack.com/archives/C01DGQ3AT09/p1623147347346700
=> fix: removed deprecated @types/multimatch

.circleci/config.yml
Latest sematic release package doesn't work with node12. until it gets fixed, we want to downgrade it to a version that was suggest as working
the current issue 
```
npx: installed 573 in 13.448s
/home/circleci/.npm/_npx/86/lib/node_modules/semantic-release/node_modules/marked/src/marked.js:158
const prevRenderer = extensions.renderers?.[ext.name];
^
SyntaxError: Unexpected token '.'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require …
```
=> fix: temporary change of semantic-release release ver. latest version is broken

src/files.ts, tests/files.spec.ts, tests/sample-repo/exclude/.snyk
This pr fixes the bug that you need to have a global and code field under excludes in the .snyk file to work
=> [PUL-235]fix: excludes with code or gloabl

src/constants.ts, src/http.ts, src/needle.ts, tests/analysis.spec.ts, tests/http.spec.ts
This PR is a replacement for [previous PR](https://github.com/snyk/code-client/pull/119) to fix the regression for IPv6 clients. We've noticed that some of the clients who don't have full IPv6 supports started to authenticate using IPv6 which broke their VS Code extension.
Some users encountered ENETUNREACH error instead of EADDRNOTAVAIL as wrongly assumed in the previous fix PR. Thus we shouldn't rely on specific error, rather on an error. This is how it was before the refactoring around http took place and is consistent with Snyk CLI code.
This fixes the following issues:
https://snyk.slack.com/archives/C026PS65XA8/p1642092098003500
https://snyk.slack.com/archives/C01FA88CUU9/p1641979366003300?thread_ts=1641978929.003100&cid=C01FA88CUU9 …
=> fix: getIpFamily - do not expect specific error for clients without IPv6

src/files.ts
Glob determines changed files as removed, when bundle gets extended currently on Windows environments.
The problem arises due to a use of backslashes when passing glob pattern to fast-glob library. As [fast-glob documentation states](https://github.com/snyk/fast-glob#how-to-write-patterns-on-windows), forward slashes should be used instead on Win environments.
It would be great to run automates tests on Windows environment to pick up those type of issues in future. I expect "extend bundle files" test should pick the problem up, when tested under Windows.
=> fix: glob matching in extending bundle on Windows [ROAD-650]

tests/analysis.spec.ts
Here we don't really care about the length of results and having a set
number for amount of issues makes this test prone to flakiness.  We are more
interested whether the bundle was extended properly.
=> test: remove precise length for results

src/needle.ts
Increasing connection timeout - one of the things needed for monoliths
=> fix: monoliths repo no longer timeouts

.github/CODEOWNERS
Zenith doesn't seem to have their Github org setup correctly yet, removing Nebula's ownership
=> chore: Transferring ownership to Zenith NEBULA-492

src/bundles.ts, src/http.ts, tests/analysis.spec.ts, tests/api.spec.ts, tests/bundle.spec.ts, tests/constants/sample.ts
This PR adds the capability to `base64` encode payloads created by the `snyk code test` with the `options.base64Encoding` flag.
This feature is added to allow `base64` encoded payloads to be passed to `deeproxy` for single-tenant solutions, obfuscating source code and preventing Akamai WAF rules incorrectly flagging code transmitted in the payload.
Enabling `base64` encoding requires `deeproxy` to be deployed *and* with the `base64` encode flag enabled also.
https://snyksec.atlassian.net/browse/NEBULA-520
=> feat: Support Base64 encoding

src/needle.ts
When calling upstream services, depending on the HTTP code returned we may retry up to 10 times. This already applies to 503, 502,421, 504 and 452 but NOT 500's
If we get a 500 back we don't retry and immediately return a failure. This PR changes it so that on 500's we do the retries, this should help network/application resiliency.
=> fix: retry on when getting 500 resp

src/http.ts, tests/http.spec.ts
It enables VS Code extension to authenticate using `https://app.eu.snyk.io` authentication host in multi-tenant.
The route to the verify/callback API endpoint has been changed, see [this thread](https://snyk.slack.com/archives/C038SPUVBEU/p1656600323231699).
=> fix: support multi-tenant EU auth verification [ROAD-917]

src/http.ts
GET requests with a request body are rejected at GKE ingress
=> fix: remove body from GET /report/{reportId} request

src/http.ts, src/interfaces/analysis-options.interface.ts, tests/api.spec.ts, tests/report.spec.ts
Add support and handling for additional report-related params:
- `targetName` (from CLI: `target-name`)
- `targetRef` (from CLI: `target-reference`)
- `remoteRepoUrl` (from CLI: `remote-repo-url`)
CLI companion PR: https://github.com/snyk/cli/pull/4484
TODO:
=> fix: add support for additional report parameters [ZEN-556]

src/http.ts
I am changing the AuthN logic to only send the token through the `Authorization` header instead of sending both `session-token` and a dummy `Authorization`.
This change relies on this [Deeproxy PR](https://github.com/snyk/deeproxy/pull/336) 
In the Deeproxy PR, there is more context on this AuthN change and a diagram of all Deeproxy consumers and how they are affected by this change.
=> fix: Send valid `Authorization` header

package.json, tests/__snapshots__/files.spec.ts.snap, tests/api.spec.ts, tests/constants/sample.ts, tests/files.spec.ts
Following a minor update to `fast-glob` (version `3.3.0`), we are seeing different behaviour for the `searchFiles` function.
The new behaviour is actually the correct one, as there was no reason for `exclude/.snyk` to not have been detected beforehand, so the update seems correct and the tests were updated to reflect the new behaviour.
Furthermore, instead of checking an individual file in the `collect bundle files` test we now check all of the items returned against a snapshot. This will make it much clearer when/if anything changes between the snapshot and actual results.
=> fix: file tests after fast-glob update

README.md, package.json, src/analysis.ts, src/http.ts, src/index.ts, src/interfaces/analysis-options.interface.ts, src/interfaces/analysis-result.interface.ts, src/report.ts, tests/analysis.spec.ts, tests/constants/sample.ts, tests/report.spec.ts
Adds support for analysing existing SCM projects and reporting results to the platform.
A new exported method is defined called `analyzeScmProject`, which clients can call in order to trigger the SCM analysis/test flow.
The underlying behaviour is similar to the `analyzeFolders` method when `reportOptions.enabled` is `true`, with the main difference being that it does not create a bundle first (since the code is available in a remote repo, a bundle is not needed).
Otherwise it follows the existing logic we have for triggering and polling tests and returning the results once finished, but using dedicated API endpoints (i.e. `/test` instead of `/report`).
=> feat: implement support for SCM-based analyses with reporting

tests/analysis.spec.ts, tests/api.spec.ts
Updates expected coverage after API deduplication changes (https://github.com/snyk/sast-analysis-api/pull/414).
In an attempt to fix pipeline flakes, this PR also:
- Replaces `Set` comparisons for coverage with `jest-extended`'s `toIncludeSameMembers` matcher.
- Updates expected number of `onScanFilesProgress` events to match number of files in Bundle.
=> test: fix tests

src/report.ts, tests/report.spec.ts
Remove the project name limit of 64 characters for the files report flow.
https://snyk.slack.com/archives/C01DGQ3AT09/p1689238829165069
=> fix: remove project name limit from file report flow [ZEN-748]

src/bundles.ts, src/files.ts, src/interfaces/analysis-options.interface.ts, tests/__snapshots__/files.spec.ts.snap, tests/constants/sample.ts, tests/file-ignores.spec.ts, tests/files.spec.ts, tests/fixtures/file-ignores/combined/.dcignore, tests/fixtures/file-ignores/combined/.gitignore, tests/fixtures/file-ignores/combined/.snyk, tests/fixtures/file-ignores/combined/snyk-root-excluded/.gitignore, tests/fixtures/file-ignores/combined/sub/.snyk, tests/fixtures/file-ignores/combined/sub/snyk-deep-excluded/.gitignore, tests/fixtures/file-ignores/combined/sub/snyk-nested-excluded/.gitignore, tests/fixtures/file-ignores/dot-dcignore-rules/.dcignore, tests/fixtures/file-ignores/dot-gitignore-rules/.gitignore, tests/fixtures/file-ignores/dot-snyk-excludes/.snyk, tests/fixtures/file-ignores/dot-snyk-excludes/sub/.snyk, tests/fixtures/file-ignores/negative-overrides/.gitignore, tests/fixtures/file-ignores/negative-overrides/.snyk
Addresses logic bugs in the behaviour of file excludes and ignore rules.
Current (incorrect) behaviour:
- it collects all exclude/ignore rules from all supported files in the directory, including from directories excluded by the root-level .snyk file
- i.e. if a directory `sub` is excluded by the top-level `.snyk` file, we still traverse it and collect any supported ignore files, which is unexpected and wrong behaviour - excluded directories should not be traversed at all.
- it applies negative match rules, which in some cases can override the .snyk exclude rules
- i.e. if a `.snyk` exclude is defined for a directory or file `sub`, and there is a negative match for the same directory or file in the `.gitignore` file (`!sub`), `sub` will not be excluded as expected.
In short, these fixes …
=> fix: file exclude behaviour [ZEN-588]

src/http.ts, src/utils/httpUtils.ts, tests/httpUtils.spec.ts
Adding logic to route to gateway instead of the deeproxy service
src/utils/httpUtils.ts
You can run the tests
For a temporary stage where some Deeproxy changes only deployed to FedRAMP we add this logic to use the new Deeproxy arch' in the FedRAMP clusters. 
When the changes are deployed to all the clusters we can use this new logic as default logic.
=> feat: add routing to GW option for sast

src/http.ts, src/interfaces/json-api.ts, src/needle.ts, src/utils/httpUtils.ts, tests/http.spec.ts, tests/httpUtils.spec.ts
- Adds error handling for catalogue (json api format) errors to throw errors with a detail
- Handles analysis and create/extend bundle requests to detail [limit errors](https://docs.snyk.io/more-info/error-catalog#code) thrown by SAA and FBS
- Will be used in [this](https://github.com/snyk/cli/pull/4922) PR for the CLI to display error to the user
- User will see error message + user friendly detail + link to error catalogue
=> feat: add error handling for limit errors

src/bundles.ts, src/http.ts, tests/api.spec.ts, tests/http.spec.ts
- [PUL2-771] Linked to Jira ticket
Getting the filters works without Authorization header in all environments. In FedRamp, this is not allowed, so I am addig the possibility to use the extra headers when getting the file extension in code-client.
This is required for the e2e test orb to work with FedRamp-Alpha.
[PUL2-771]: https://snyksec.atlassian.net/browse/PUL2-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add posibility to add extra headers to filters endpoint

package-lock.json, package.json
- Downgrades needle to 3.0.0
- See https://github.com/snyk/cli/pull/4953 for the corresponding CLI change
- See https://github.com/tomas/needle/issues/406 for the bug report in needle
=> fix: downgrade needle for CONNECT mode proxy support

package-lock.json, package.json, src/needle.ts
Upgrades needle and disables needle from picking up the proxy based on environment variables.
Essentially reverting the temporary downgrade of https://github.com/snyk/code-client/pull/217 and properly fixing proxy support.
Related to https://github.com/snyk/cli/pull/4967
=> fix: upgrade needle and disable proxy in needle

.circleci/config.yml
These secrets were previously injected via project-specific environment variables. The secrets have been regenerated and moved into a [CircleCI context](https://app.circleci.com/settings/organization/github/snyk/contexts/4dc64971-d968-4f6c-812f-37caec3ab934).
=> fix: add code-client-integration-test context to tests
