snyk/code-client

CHANGELOG.md
package-lock.json
package.json
src/constants/errors.ts
src/dto/report-error.response.dto.ts
src/dto/report-telemetry.request.dto.ts
src/dto/report-telemetry.response.dto.ts
src/enums/request-types.enum.ts
src/index.ts
src/interfaces/service-ai.interface.ts
src/modules/Http.ts
src/modules/ServiceAI.ts

Step 2 of: https://deepcodeai.atlassian.net/browse/COL-729
(requires https://github.com/DeepCodeAI/product/pull/505)

Report telemetry api

---

src/analysis.ts
src/bundles.ts

Optimization of bundle creation and upload for huge repositories by uploading files for each bundle before extending it

Optimization for huge repositories

---

src/analysis.ts
src/http.ts
tests/analysis.spec.ts
tests/api.spec.ts

- added waiting status to expected response statuses
- adjusted one test of analysis with missing files;
- fixed one test case with changed suggestion message

Waiting status

---

CHANGELOG.md
package.json
src/analysis.ts
src/files.ts
src/http.ts

- Error-tolerant handling of issues with file access permissions
- Additional handling of "socket hangup" network issue

Misc fixes

---

CHANGELOG.md
package.json
src/analysis.ts
src/interfaces/analysis-result.interface.ts
src/sarif_converter.ts
tests/api.spec.ts
tests/git.analysis.spec.ts

new fields in suggestion:

---

src/sarif_converter.ts
tests/git.analysis.spec.ts

Remove unnecessary parts and keep the rule id as LANGUAGE/RULE
Ref: https://snyksec.atlassian.net/browse/COD-29

fix: stabilise rule id in sarif

---

CHANGELOG.md
package-lock.json
package.json
src/analysis.ts
src/bundles.ts
src/files.ts
tests/analysis.spec.ts
tests/api.spec.ts
tests/constants/sample.ts
tests/files.spec.ts
tests/git.analysis.spec.ts
tests/sample-repo/only_text/readme.md

- better error handling related to local files;
- better handling of empty bundles;

Bug fixing

---

src/sarif_converter.ts
tests/git.analysis.spec.ts

[COD-33]Feat: add highlighting to sarif converter

---

CHANGELOG.md
README.md
package-lock.json
package.json
tests/analysis.spec.ts
tests/api.spec.ts

deprecated notice;
tests fixed

last version;

---

src/sarif_converter.ts
tests/api.spec.ts
tests/fixtures/sarif_convertor/analysis-results-without-fingerprinting.json
tests/git.analysis.spec.ts
tests/sarif_converter.spec.ts

[COD-133]
This change introduces the new fingerprinting functionality (https://github.com/snyk/octopus/pull/706) as part of the `Code-Client` library as well.
[COD-133]: https://snyksec.atlassian.net/browse/COD-133

[COD-133] feat: add fingerprintings for Sarif output

---

src/sarif_converter.ts

Fixing CR comments from https://github.com/snyk/code-client/pull/47

chore: code improvements

---

src/index.ts

we want the consumers of this client to be able
to better type input for client usage

chore: export AnalysisSeverity interface

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Add to our repo:
* Snyk Code ownership
* PR template 
* Feature request template

chore: add CodeOwner + PR template

---

package.json
src/analysis.ts
src/bundles.ts
src/files.ts

This pr imports lodash single functions instead of the full lodash package.

chore: update lodash to import single functions

---

development.md
package.json
src/analysis.ts
src/axios.ts
src/constants.ts
src/http.ts
tests/analysis.spec.ts
tests/api.spec.ts
tests/constants/base.ts

Authentication functions where rewritten to work with Snyk API
Tests partially cover this case. I did not find a way to test successful workflow automatically
This is braking change for Deepcode integration, as client will not be able to obtain Deepcode API token

[COD-120] Authentication functionality via Snyk API

---

development.md

BREAKING CHANGE: authentication functions were changed

feat: auth

---

src/sarif_converter.ts
tests/__snapshots__/git.analysis.spec.ts.snap
tests/git.analysis.spec.ts
tests/sarif_converter.spec.ts

[COD-254]
Fix an issue where ff there are multiple places, where same issue happens, they are lost during conversion to Sarif.
[COD-254]: https://snyksec.atlassian.net/browse/COD-254

[COD-254] fix: wrong number of calculated issues as part of the Sarif conversion

---

package.json
src/cache.ts
src/files.ts
tests/__snapshots__/api.spec.ts.snap
tests/api.spec.ts
tests/cache.spec.ts

This PR removes the dependency flat-cache that was causing execution issues in the cli due to the export types.
Our implementation only covers the functionality we need and does not support circularJSON

fix: flat-cache removed own custom implementation 

---

src/analysis.ts
src/http.ts
src/interfaces/http-options.interface.ts
tests/__snapshots__/api.spec.ts.snap
tests/analysis.spec.ts
tests/api.spec.ts
tests/git.analysis.spec.ts

Adds support for adding custom request options that could be propagated to API server. Headers are currently supported.
As usual, in tests :-)
By complicated manual setup :-)

feat: add support for custom request options

---

tests/api.spec.ts

Fixing tests after staging update.

test: fix tests after staging update

---

.circleci/config.yml

Explicitly set working dir for CircleCI
CircleCI failing due to issues with implicit working dir https://app.circleci.com/pipelines/github/snyk/code-client/202/workflows/4a803728-ab5c-474e-aca6-aa3f04b19998/jobs/260

chore: explicitly set working dir for CircleCI

---

.circleci/config.yml

Changed order of restore_cache and checkout to fix circleci

chore: fixed cache of CircleCI

---

src/analysis.ts
src/http.ts
src/interfaces/analysis-options.interface.ts
tests/api.spec.ts

Adding support for reachable analysis results 
*This is Is currently blocked by https://github.com/snyk/octopus/pull/772 . as the tests on code client  are making calls to the API server. so will merge after confirming it's working on the API server*

[COD-214]feat: add support for reachability analysis call

---

src/analysis.ts
src/interfaces/analysis-options.interface.ts

- Adds missing reachability args to enable reachability via `analyzeGit`
- Adds additional tests

COD-409/add reachability args

---

tests/files.spec.ts

feat: Improved folder scanning performance

---

tests/analysis.spec.ts
tests/api.spec.ts

Adjusting test to support new languages (c++ beta)

fix: add missing c++ test support

---

src/analysis.ts
src/files.ts
src/index.ts
src/interfaces/analysis-options.interface.ts
tests/__snapshots__/api.spec.ts.snap
tests/analysis.spec.ts
tests/api.spec.ts
tests/bundle.spec.ts
tests/constants/sample.ts
tests/files.spec.ts

[NEB-44]
Added the result merge for extended analyses by parsing the sarif results.
All input (i.e. `extendAnalysisOptions.files`) and output (i.e. sarif positions) are always to be considered relative to `baseDir` now for consistency.
[NEB-44]: https://snyksec.atlassian.net/browse/NEB-44

[NEB-44] fix: fixed result merge for extended analysis

---

src/analysis.ts
src/http.ts
src/interfaces/analysis-options.interface.ts
tests/analysis.spec.ts

new param is added "prioritized" to granularly configure usual vs special cases.
Currently it's going to be used to prioritize pingdom checkers

feat: added "prioritized" param to function analyzeFolder in old API

---

package.json
src/bundles.ts
src/constants.ts
src/files.ts
tests/bundle.spec.ts
tests/constants/sample.ts
tests/files.spec.ts
tests/sample-repo/.snyk
tests/sample-repo/exclude/excluded-file.js
tests/sample-repo/exclude/excluded-folder/excluded-folder-file.js

Adds the ability to exclude files from the analysis bundle when adding them under the `exclude` section in `.snyk` file
Nothing specific 
Adding entries to a repo's `.snyk` file under the `exclude` field (same as in the sample-repo inside under `tests` folder) and making sure they're not sent for analysis.

feat: exclude files from bundle with .snyk

---

src/index.ts
tests/analysis.spec.ts

Currently, we need to be able to use this function in uptime checkers

feat: exported getAnalysis function to conduct on call to our API only

---

src/files.ts
tests/constants/sample.ts
tests/sample-repo/.snyk

chore: added a parsing of "global" exclusion configuration

---

tests/files.spec.ts

This PR exists only yo bump a new version using semantic releases

fix: fixed test

---

src/files.ts
tests/analysis.spec.ts

Remove unnecessary logging when the `.snyk` policy file is not found.

fix: remove missing policy file log

---

src/bundles.ts
src/constants.ts
src/files.ts
tests/analysis.spec.ts
tests/constants/sample.ts
tests/files.spec.ts

This PR now allows the everything using code-client to use .snyk file

fix: dot-snyk files respected

---

tests/analysis.spec.ts
tests/api.spec.ts

The Engine constantly gets improved. This PR aligns our tests to it, because now it finds more issues in our sample project

chore: adjusted tests according to latest engine improvements

---

src/analysis.ts
src/bundles.ts
src/files.ts
src/index.ts
src/interfaces/analysis-options.interface.ts
src/interfaces/files.interface.ts
tests/analysis.spec.ts
tests/api.spec.ts

Move some interface exports to their dedicated files

chore: reorganize interfaces exports

---

src/analysis.ts
src/http.ts
src/index.ts
src/interfaces/analysis-options.interface.ts
tests/analysis.spec.ts

Adds additional metadata and context on the analysis request. This will allow `code-client` consumers to forward this data for the analysis request and help us gather this data to create new metrics.

feat: add additional context for analysis request

---

src/analysis.ts
src/bundles.ts
src/http.ts

https://snyksec.atlassian.net/browse/NEBULA-339
Ignore the request ID difference in one of the screenshots 🙃

feat: better observability [NEBULA-399]

---

src/interfaces/analysis-options.interface.ts

in code_api, analysis context is a completely different object. The
change will make sure that we are passing the right parameters from CLI
or IDE
- 
- 
-
-
-

feat: align analysis context

---

src/analysis.ts
src/bundles.ts
src/interfaces/analysis-options.interface.ts

feat: adding support for beta language flags in cli

---

src/analysis.ts
src/constants.ts
tests/analysis.spec.ts

We currently don't properly handle undefined "analysisContext". This PR fixes it.
Also, it cleans constants a bit and fixes tests

fix: fixed tests and handling of optional argument analysisContext

---

.circleci/config.yml
.eslintignore
.eslintrc.json
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md
.prettierignore
README.md
development.md
package.json
src/bundles.ts
src/cache.ts
src/files.ts
src/http.ts
tests/auth.api.spec.ts
tests/files.spec.ts
tests/fixtures/sarif_convertor/analysis-results-without-fingerprinting.json
tests/fixtures/sarif_convertor/shallow_sast_webgoat/jquery.form.js
tests/http.spec.ts
tests/sarif-schema-2.1.0.json
tsconfig.json

chore: add-lint-to-pipeline

---

src/http.ts
tests/api.spec.ts

- Automatically sets `base64encoding` based on the `baseURL` provided. This supports the new EU environments by auto-enabling payload encoding/compression.
- See changes made in `http.ts`
- Execute `npm test` against different endpoints and verify behaviour
- This change supports new EU-hosted environments, allowing CLI/other consumers to correctly encode/compress payloads without end-user config.

[NEBULA-632] feat/enable-base64-encoding-for-mt-eu

---

.snyk
tests/api.spec.ts

Adds exclude rule for `tests`.
Updates test for filters.

chore: add policy file with excludes for tests

---

src/analysis.ts
src/http.ts
src/index.ts
src/interfaces/analysis-options.interface.ts
src/interfaces/analysis-result.interface.ts
src/interfaces/files.interface.ts
src/report.ts
tests/analysis.spec.ts
tests/api.spec.ts
tests/report.spec.ts

- Adds the report feature to code-client
- Adds tests to the report feature
Related: [cli PR](https://github.com/snyk/cli/pull/4422)
This `code-client` version been successfully tested with the current `cli` version to confirm no breaking changes were made.
[ZEN-494]: https://snyksec.atlassian.net/browse/ZEN-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ZEN-495]: https://snyksec.atlassian.net/browse/ZEN-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add report upload to code test [ZEN-494]

---

src/bundles.ts
src/index.ts

fix: separated of getting supported files from creating remote bundle.
This refactoring is needed for improved internal testing.
Note: No external API is changed.
https://snyksec.atlassian.net/browse/ZEN-529

fix: separated of getting supported files from creating remote bundle

---

src/bundles.ts
src/index.ts

This tiny PR exports one function getSupportedFiles.
It's required inside deeproxy systemcheck
https://snyksec.atlassian.net/browse/ZEN-529

fix: export function getSupportedFiles for internal testing in deeproxy

---

src/bundles.ts
src/http.ts
tests/bundle.spec.ts

This is also a continuation of changes required to make deeproxy's "systemcheck" call properly communicate with backend services.
This PR adds an optional parameter for public user id. This is required as our files-bundle-store requires it: https://github.com/snyk/files-bundle-store/blob/main/src/api/rest/middleware/auth.ts#L8
related jira ticket: https://snyksec.atlassian.net/browse/ZEN-529

feat: added an optional parameter for public user identificator

---

tests/analysis.spec.ts
tests/api.spec.ts
tests/constants/sample.ts
tests/report.spec.ts

Adds missing report tests from #170
[ZEN-537]: https://snyksec.atlassian.net/browse/ZEN-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add report tests [ZEN-537]

---

README.md
package.json
src/bundles.ts
src/cli.ts
src/files.ts

During my load tests i was struggling due to additional configurations required when used Code client via Snyk CLI.
Especially, if I wanted to adjust code-client code a bit and see it's affect on performance/stability.
Also, i wanted to have a isolated functionality to only create bundle, without running analysis on it.
This PR adds a CLI, that allows to do so.
Example usage:
```bash
$ time npm run cli -- bundle:create --url="<deeproxy url or directly files-bundle-store>" --token="snyk token" --headers="custom-header: test-user" --patterns=".*" --path="<path to source code>"
```

feat: added CLI

---

tests/api.spec.ts

updated tests according to new Code services

fix: updated tests according to new Code services

---

.circleci/config.yml
.gitleaksignore

- Adds the prodsec secret scanning CircleCI orb
https://snyksec.atlassian.net/browse/ZEN-654

chore: add secret scanning

---

src/files.ts
tests/files.spec.ts
tests/sample-repo/invalid-dot-snyk/.snyk.invalid

Makes an error that is thrown in case of invalid ignore rules in .snyk more informative 
https://snyksec.atlassian.net/browse/ZEN-733
Run snyk code test -d over [Snyk CLI](https://github.com/snyk/cli) repository
https://snyk.slack.com/archives/C01DGQ3AT09/p1690922427417839?thread_ts=1689170972.097249&cid=C01DGQ3AT09

fix: descriptive error when .snyk contains invalid ignores

---

src/http.ts

Places a proper placeholder org-id for filters endpoint, so it passes regex validation in the gateway.

fix: placeholder org-id fix

---

src/bundles.ts
src/cli.ts
src/http.ts

fix: add orgId for filters endpoint as well

---

src/bundles.ts
src/cli.ts
src/report.ts

fix: add orgId to code-client calls

---

src/http.ts
src/interfaces/json-api.ts
src/needle.ts
src/utils/httpUtils.ts
tests/analysis.spec.ts
tests/api.spec.ts
tests/fixtures/sarif_convertor/analysis-results-without-fingerprinting.json
tests/http.spec.ts
tests/httpUtils.spec.ts

Applies Snyk Code standards when handling [Snyk catalog errors ](https://docs.snyk.io/more-info/error-catalog#snyk-error-codes).

fix: standardised Snyk catalog errors handling

---

.circleci/config.yml
catalog-info.yaml

chore: add quality gates

---

package-lock.json
package.json

Follow-up on https://github.com/snyk/code-client/pull/227 to remove override for the fast-glob's micromatch dependency. Fast-glob was updated with the CVE fix in it.
This PR should simplify library consumption, especially as there's a known bug with overrides consumption in `npm install`: https://github.com/npm/cli/issues/5850

feat: update fast-glob with latest micromatch

---

.github/CODEOWNERS

update team name in codeowners
n/a

chore: update codeowners [wr-810]
